name: Magic Number Guess

on:
  workflow_dispatch:

jobs:
  run-magic:
    runs-on: ubuntu-latest
    env:
      MIN_RIDDLE_SECRET: ${{ vars.MIN_RIDDLE_SECRET }}

    steps:
      - name: Print Riddle Secret
        run: echo "$MIN_RIDDLE_SECRET"

      - name: Guess the Magic Number
        run: |
          MAGIC_NUMBER=$((RANDOM % 100 + 1))
          echo "Our magic number is: $MAGIC_NUMBER"
